version: 2.1
jobs:
  configure_infrastructure:
     docker:
       - image: python:3.7-alpine3.11
     steps:
       - checkout
       - add_ssh_keys:
       #Ansible will have the creds it needs to access the EC2 instance
          fingerprints:  ["5a:70:c9:12:ae:d8:6e:01:b4:19:66:23:53:06:bf:60"]
       - run:
         name: Install dependencies
         command: |
           apk add --update ansible   
       - run:
          name: Configure server
          command: |
            ansible-playbook -i inventory.txt main.yml
workflows:
  my_workflow:
    jobs:
      - configure_infrastructure            